[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build.meta"

[project]
name = "stellar_matchmaker"
version= "0.0.1"

dependencies = [
    "numpy", "astropy", "matplotlib", "astroquery"
]
